name: 'clock in'

on:
  push:
  schedule:
  #每天早上8点20  UTC0加8个钟
    - cron: '20 0 * * *'

jobs:
  start: 
    runs-on: ubuntu-latest
    steps:
      - name: 'curl api'
        run: curl https://lingu-nextjs-cron.vercel.app/api/cron/clockin
